name: Test

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node Dependencies
        run: npm ci
      - name: Check Prettier
        run: npm run prettier
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node Dependencies
        run: npm ci
      - name: Vite Build
        run: npm run build
